version: "3.7"

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres_movies
    env_file:
      - db.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - movies_network


  django:
    build:
      context: mysite
      dockerfile: Dockerfile
    container_name: django_movies
    ports:
      - "8000:8000"
    env_file:
      - ./mysite/.env
    volumes:
      - static_volume:/data/static
    networks:
      - movies_network
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres

  movies_streaming_converter_api:
    build:
      context: converter
      dockerfile: Dockerfile
    volumes:
      - ./converter/files:/data/static
    networks:
      - movies_network
    command: ["python", "modelhandler.py", "--target-host", "django"]
    depends_on:
      - postgres

  converter_fast_api:
    build:
      context: fast_api
      dockerfile: Dockerfile
    networks:
      - movies_network
    command: ["python", "main.py"]
    depends_on:
      - postgres


#  migration:
#    image: uzman
#    command: python manage.py migrate --noinput
#    volumes:
#      - .:/code
#    depends_on:
#      - postgres

#  nginx:
#    image: nginx:1.19.2
#    container_name: nginx_movies
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./nginx/conf.d:/etc/nginx/conf.d:ro
#      - static_volume:/data:ro
#    ports:
#      - "80:80"
#    networks:
#      - movies_network
#    depends_on:
#      - django


volumes:
  static_volume:
  movies_streaming_converter_api:

networks:
  movies_network:

#docker exec -it django_movies python manage.py migrate
#docker exec -it django_movies bash
#python manage.py migrate
#docker exec -i postgres_movies bash

#2
#docker exec -t -i postgres_movies bash
#python manage.py makemigrations
#python manage.py migrate


#3
#docker-compose exec postgres_movies python manage.py makemigrations
#docker-compose exec postgres_movies python manage.py migrate