# Generated by Django 4.1 on 2022-09-01 17:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fileupl",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "file_path",
                    models.FileField(upload_to="files/", verbose_name="File"),
                ),
                (
                    "resolution",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Resolution"
                    ),
                ),
                (
                    "codec_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Codec"
                    ),
                ),
                (
                    "display_aspect_ratio",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Display Aspect Ratio",
                    ),
                ),
                ("fps", models.IntegerField(blank=True, null=True, verbose_name="FPS")),
            ],
            options={
                "verbose_name": "Fileupl",
                "verbose_name_plural": "Fileupl",
                "ordering": ["file_path"],
            },
        ),
        migrations.CreateModel(
            name="FilmWork",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "certificate",
                    models.TextField(blank=True, verbose_name="Certificate"),
                ),
                (
                    "file_path",
                    models.FileField(
                        upload_to="film_works/", verbose_name="Original file"
                    ),
                ),
            ],
            options={
                "verbose_name": "Film",
                "verbose_name_plural": "Films",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=200)),
                ("votes", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.question"
                    ),
                ),
            ],
        ),
    ]
