# Generated by Django 4.1 on 2022-08-31 12:48

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "file_path",
                    models.FileField(upload_to="files/", verbose_name="File"),
                ),
                (
                    "resolution",
                    models.CharField(max_length=100, verbose_name="Resolution"),
                ),
                (
                    "codec_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Codec"
                    ),
                ),
                (
                    "display_aspect_ratio",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Display Aspect Ratio",
                    ),
                ),
                ("fps", models.IntegerField(blank=True, null=True, verbose_name="FPS")),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
                "ordering": ["file_path"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FileFilmWork",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_created=True, auto_now_add=True, verbose_name="Created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FilmWork",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "certificate",
                    models.TextField(blank=True, verbose_name="Certificate"),
                ),
                (
                    "file_path",
                    models.FileField(
                        upload_to="film_works/", verbose_name="Original file"
                    ),
                ),
            ],
            options={
                "verbose_name": "Film",
                "verbose_name_plural": "Films",
                "ordering": ["title"],
                "managed": False,
            },
        ),
    ]
