# Generated by Django 4.1 on 2022-09-02 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_filefilmwork_filmwork_files_filefilmwork_film_work_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filmwork",
            name="files",
        ),
        migrations.AddField(
            model_name="fileupl",
            name="film",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="film",
                to="polls.filmwork",
                verbose_name="Фильм",
            ),
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
