# Generated by Django 4.1 on 2022-09-04 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_remove_filmwork_files_fileupl_film_delete_choice_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filmwork",
            options={
                "ordering": ["title"],
                "verbose_name": "File",
                "verbose_name_plural": "Files",
            },
        ),
    ]
