# Generated by Django 4.1 on 2022-09-04 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_alter_filmwork_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filmwork",
            options={
                "ordering": ["title"],
                "verbose_name": "Film",
                "verbose_name_plural": "Films",
            },
        ),
        migrations.AlterField(
            model_name="fileupl",
            name="film",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file",
                to="polls.filmwork",
                verbose_name="Фильм",
            ),
        ),
    ]
