# Generated by Django 4.1 on 2022-09-04 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_alter_filmwork_options_alter_fileupl_film"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupl",
            name="film",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="polls.filmwork",
                verbose_name="Фильм",
            ),
        ),
    ]
