# Generated by Django 4.1 on 2022-09-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_alter_fileupl_film"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
            ],
        ),
    ]
