# Generated by Django 4.1 on 2022-09-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="file_path",
            field=models.FileField(
                blank=True, null=True, upload_to="files/", verbose_name="FileQuestion"
            ),
        ),
    ]
